---

- name: Create group for users allowed to SSH in
  group:
    name: "{{ deflect_ssh_allow_group_name }}"
    state: present

- name: Add allowed users to SSH group
  user:
    name: "{{ item.login }}"
    groups: "{{ deflect_ssh_allow_group_name }}"
    state: present
    append: yes
  with_items: "{{ deflect_ssh_users }}"

